In [2]:
#Indexing

import numpy as np

# Array erzeugen: 1 bis 100 als (10, 10)
arr = np.arange(1, 101).reshape(10, 10)
print("Originales Array:")
print(arr)

# a) 1., 5. und letzte Zeile
print("\na) Zeilen 1, 5 und letzte:")
arr = np.arange(1, 101).reshape(10, 10)
print(arr[[0, 4, 9]])

# b) 3. und 7. Spalte in ungeraden Zeilen
print("\nb) 3. und 7. Spalte in ungeraden Zeilen:")
arr = np.arange(1, 101).reshape(10, 10)
print(arr[1::2, [2, 6]])

# c) 3x3 Subarray links oben
print("\nc) 3x3 links oben:")
arr = np.arange(1, 101).reshape(10, 10)
print(arr[:3, :3])

# d) 2. und 4. Zeile negativ machen
arr = np.arange(1, 101).reshape(10, 10)
arr[[1, 3]] = -arr[[1, 3]]
print("\nd) Nach Negativ-Machen der 2. und 4. Zeile:")
print(arr)

# e) Alle Werte < 25 durch 0 ersetzen
arr = np.arange(1, 101).reshape(10, 10)
arr[arr < 25] = 0
print("\ne) Nach Ersetzen aller < 25 durch 0:")
print(arr)

Originales Array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

a) Zeilen 1, 5 und letzte:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 91  92  93  94  95  96  97  98  99 100]]

b) 3. und 7. Spalte in ungeraden Zeilen:
[[13 17]
 [33 37]
 [53 57]
 [73 77]
 [93 97]]

c) 3x3 links oben:
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]

d) Nach Negativ-Machen der 2. und 4. Zeile:
[[  1   2   3   4   5   6   7   8   9  10]
 [-11 -12 -13 -14 -15 -16 -17 -18 -19 -20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [-31 -32 -33 -34 -35 -36 -37 -38 -39 -40]
 [ 41  42  43  44  45  46  47  